publish:

  asset:
    repo_url: <s3_bucket_url>

  image:
    repo_url: 066396987149.dkr.ecr.us-east-1.amazonaws.com
    repo_name: aso-integration-repository

promote:

  stages:

    dev:
      cluster_name: aso-shared-services-dev

    qa:
      cluster_name: aso-shared-services-qa

    prod:
      cluster_name: aso-shared-services-prod
